### ISSUE TITLE
How to insert Picture ?

### ISSUE THREAD

**Issue by dgillier** [Qoraiche/laravel-mail-editor#100]
I know that the doc is online, but can't find a way to insert an image into a template with {{asset('img/brand/bms_logo_black.png')}}...

Preview are not really working (pict is correctly displayed depending on where...).

<img width="1155" alt="Screenshot 2020-06-09 at 15 44 56" src="https://user-images.githubusercontent.com/37960204/84155169-55248980-aa68-11ea-8217-e3a0715c5acd.png">
<img width="1118" alt="Screenshot 2020-06-09 at 15 45 08" src="https://user-images.githubusercontent.com/37960204/84155179-5655b680-aa68-11ea-9264-4dad35ab9cc1.png">
<img width="1242" alt="Screenshot 2020-06-09 at 15 45 18" src="https://user-images.githubusercontent.com/37960204/84155181-56ee4d00-aa68-11ea-987e-735678645d5f.png">

What is the right way to do it if any ?
Thanks, Denis

**Comment by Elshaden** [comment]
Hi @dgillier 
Did you get any resolution to this problem???

Thanks

**Comment by Alina-chan** [comment]
Hey @dgillier, if you are trying to output the image in your HTML code, maybe Blade will help
`<img src="@asset('img/brand/bms_logo_black.png')"/>`

**Comment by Qoraiche** [comment]
Hey, sorry for the late reply on this,
This issue happens because for the no markdown templates we are basically using the built-in WYSIWYG plugin to preview/render blade templates and not actually compiling it as we do for a markdown template, so you need to use the full image url (without using the asset or mix function) in order to preview it, anyway i have added this to our future improvments.

Thanks
