### ISSUE TITLE
Trying to access array offset on value of type int

### ISSUE THREAD

**Issue by SergioWiesner** [Qoraiche/laravel-mail-editor#102]
**BUG**

I just installed the package in my application and I have tried to create the first template and it shows me in the logs "Trying to access array offset on value of type int"

**To Reproduce**
1. Install the package
2. go to url "/maileclipse/mailables"
4. Add new mailable an create a new mailable
5. Show message "error 500" and you see the logs and say "Trying to access array offset on value of type int ......."

**Laravel Application**:  5.7.*

**Maileclipse package version**: ^2.0

![error](https://user-images.githubusercontent.com/5554583/84212837-8c089880-aa84-11ea-9c79-067464df8860.PNG)
![Captura](https://user-images.githubusercontent.com/5554583/84212893-b35f6580-aa84-11ea-9113-dc1a4d0f6fdc.PNG)

**Comment by ReeceM** [comment]
Hi @SergioWiesner, would you be able to share that log file in an actual text form?

Also, had you modified the file already or was this in the making the template part?

**Comment by ReeceM** [comment]
This is tagged as I haven't been able to reproduce it, and also it isn't clear if this is an error from the maileclipse class or something to do with the artisan command for creating mails. 

If anyone else has this issue, please could you share the steps to reproduce.

Many Thanks in advance

**Comment by Qoraiche** [comment]
Hey @ReeceM, from the stack trace he provides looks like it's caused by the `MaileblesController@generateMailable` method, @SergioWiesner can you please tell us what PHP version you're using, also it's a known issue with laravel incompatible PHP version (mostly PHP **7.4**) (https://github.com/laravel/framework/issues/30737), thank you

**Comment by ReeceM** [comment]
> from the stack trace he provides looks like it's caused by https://github.com/Qoraiche/laravel-mail-editor/blob/master/src/MailEclipse.php#L420

Hi @Qoraiche I saw that too, and it's the method that calls the console command, then it seems the error comes from either the Artisan class itself when parsing the parameters or because of something the `generateMailables()` method passed to it. 

It does seem that is related to that issue in the Laravel framework. It would be nice to know what caused it or if it was just a once off issue 🤷‍♂️
