### ISSUE TITLE
Weird naming behaviour

### ISSUE THREAD

**Issue by phadaphunk** [Qoraiche/laravel-mail-editor#136]
**Describe the bug**
The naming behaviour is weird. It will lowercase your whole name and add Mail at the end. It does not respect the PascalCase if multiple words are in the name. Also, if you have the word `email` at the end of the name it won't add the word Mail but will lowercase the word email which makes it inconsistent with the rest.

**To Reproduce**
Create a new Mailable via the UI with the following names.

------

- **Input** : ConfirmationEmail
- **Expected** : ConfirmationEmail (or ConfirmationEmailMail to fit your standard)
- **Result** : Confirmationemail

-------

- **Input** : PasswordConfirmation
- **Expected** : PasswordConfirmationMail
- **Result** : PasswordconfirmationMail

-------

Another weird thing is the UI specifically gives this as example : `WelcomeUser` which is weird because it will be named `WelcomeuserMail` instead of the real input that was `WelcomeUser`. It can be renamed in the project and still work properly but it feels more like a bug to me. 

**Laravel Application**: Laravel 8 
**Maileclipse package version**:  `3.2`

**Comment by phadaphunk** [comment]
I read your tests and it seems to be... by design?

```
'CustomerMail' => 'Customermail',
'Customermail' => 'Customermail',
'Customer Mail' => 'CustomerMail',
'customer mail' => 'CustomerMail',
```

Hmm.

**Comment by ReeceM** [comment]
> I read your tests and it seems to be... by design?
> 
> ```
> 'CustomerMail' => 'Customermail',
> 'Customermail' => 'Customermail',
> 'Customer Mail' => 'CustomerMail',
> 'customer mail' => 'CustomerMail',
> ```
> 
> Hmm.

Hi @phadaphunk with regards the tests, those were done but the contributor to match the initial design by the of the package. So that can be adjusted anyways. At least we know that it gives the correct wrong result 🤣.

But yes, the naming convention is a little non-standard currently. Thank you for raising the issue on the repo.

I will see if this can be either PR'd or worked into the refactoring of the codebase. But I paused that a little as I opted to sort out the unit tests as a whole to ensure that none of the refactoring messed things up.
