### ISSUE TITLE
Endless User Email Verification

### ISSUE THREAD

**Issue by hmreumann** [Qoraiche/laravel-mail-editor#168]
## Describe the bug
After I added the User $user model to the constructor of a Markdown Email, when I refresh the page it starts sending Email Verifications.

## Reproduction steps
1. Create a Mailable.
2. Added a User $user to the constructor.
4. Click Mailables. And it starts sending Verification Emails.

## Laravel Version: 
Laravel Framework 8.57.0

## MailEclipse package version: 
versions : * v3.4.1

--- 

I have 101 users in my DB.

**Comment by ReeceM** [comment]
Hi @hmreumann, thank you for raising this. 

With your User model that you are using, are you making use of the `Illuminate\Contracts\Auth\MustVerifyEmail` contract?

If so, then I have a relatively good idea as to where the bug might be originating from then.

---

With regards the emails that will be sent out. The emails would be sent to users that are generated from the Faker library, it shouldn't be sending to actual users in your database. If so, please could you clarify that so I can check that too.

**Comment by hmreumann** [comment]
Ok, Thanks for the response.I´m not using the MustVerifyEmail.

**Comment by ReeceM** [comment]
Hi @hmreumann

I have been able to reproduce the bug my end, it only happens when the user model has the `MustVerifyEmail` added to it as an interface, this is relatively default to it.

The reason for it triggering this is because of the addition of the hydrations to Model relations as it iterates through all the methods on a class to see what it has as a return type.

Because the method to send a verification email doesn't take any arguments, it doesn't through an error or give an indication to it being called. It's method looks like below:

```php
    /**
     * Send the email verification notification.
     *
     * @return void
     */
    public function sendEmailVerificationNotification();
```

---

### Please Test the Following

If I can ask, please could you disable the following config option in the `config/maileclipse.php` configuration file.

set the value to `0`

```php
    'relation_depth' => env('MAILECLIPSE_RELATION_DEPTH', 0),
```
Or in the .env folder:

```env
MAILECLIPSE_RELATION_DEPTH=0
```

After setting this, please reload the page and see if there are any emails.

**Comment by hmreumann** [comment]
Hi @ReeceM , I did what you asked and it didn't solve the problem.
I put both the .env and in the config file the value 0, but it doesn't seem to be that.
As I told you, now the MustVerifyEmail Interface in my User Model isn't enabled.
I don't know what other info I can give you. Maybe I can try to reproduce the bug on a new repository.

**Comment by ReeceM** [comment]
> I don't know what other info I can give you. Maybe I can try to reproduce the bug on a new repository.

**If you can reproduce the bug in a new repository that would be great 👍**

As currently the only way I have it reproducing is that it is using the interface. But that is with a default Laravel install.

**Comment by ReeceM** [comment]
Hey @hmreumann, hope you are well,

Just wanting to know if you have been able to get a reproduction repository set up? 😄

**Comment by hmreumann** [comment]
Hallo, how are you? @ReeceM I couldn't. We were working with Laravel Sail, but I installed everything on a fresh application with at least both models that threw the error, but it works perfect. So it must be something else of the app we are building that is colliding with some part of Mail Eclipse.

I won't remove the repo, so maybe later when I have some time, I can try it better.

**Comment by ReeceM** [comment]
Hi @hmreumann I'm well.

That is okay if you weren't able to then. 

Because from the way the code behaves to load up the relations dynamically on it's own, I know that if the person has the trait enabled on a user model it is bound to trigger the function call to send the verification mail. 

What I am going to do is add it to an exclusion list on the function anyway to prevent further issues as it would also allow a channel in the future for PR's or end users to add their own if there are issues.

This might be best, and if it is pushed you can test it in the Sail version of the app where you had the issue the first time.

**Comment by hmreumann** [comment]
Great @ReeceM  thank you. I'll test it then and tell you the results.

**Comment by hmreumann** [comment]
@ReeceM I've just tested my original issue and now it is solved. Thanks for your work!!

**Comment by Qoraiche** [comment]
> @ReeceM I've just tested my original issue and now it is solved. Thanks for your work!!

Awesome!

**Comment by ReeceM** [comment]
> @ReeceM I've just tested my original issue and now it is solved. Thanks for your work!!

Awesome 🎆
