### ISSUE TITLE
Route closure

### ISSUE THREAD

**Issue by fridzema** [Qoraiche/laravel-mail-editor#2]
` LogicException  : Unable to prepare route [maileclipse] for serialization. Uses Closure.`

I think no further explanation is needed;)

**Comment by Qoraiche** [comment]
Thanks for reporting this,

This error happens because PHP is not able to serialize Closures (when using `route:cache` command in laravel). in the next update i will replace the route closure to a controller based route.

https://github.com/Qoraiche/laravel-mail-editor/blob/4be5aa9fd79740cf029a5654b714e30aa36262db/src/Http/routes.php#L5

**Comment by Qoraiche** [comment]
route closure replaced with controller-based route (check out commit [590a07d](https://github.com/Qoraiche/laravel-mail-editor/commit/590a07d71b77ed3f374453bf5b9e42bfedc1b2a9))
