### ISSUE TITLE
Still getting the following errors...

### ISSUE THREAD

**Issue by lstables** [Qoraiche/laravel-mail-editor#30]
I still get errors like this:

<img width="1414" alt="Screenshot 2019-05-07 at 09 14 23" src="https://user-images.githubusercontent.com/1168291/57284182-8fbf3400-70a8-11e9-8183-d7a0c8b17ad2.png">

And this:

<img width="1083" alt="Screenshot 2019-05-07 at 09 14 38" src="https://user-images.githubusercontent.com/1168291/57284198-951c7e80-70a8-11e9-8a3f-59954addc550.png">

**Comment by ReeceM** [comment]
Hi @lstables, that is caused by the fact that the mocker library doesn't account for arrays, that is something I new would be a possibility but didn't get my head around yet. 

I will be having a look at the way of adding the ability to have an array, as just type hinting will not allow it to be multidimensional.

As with regards your second error. If you make the `data` attribute on the Mailable `public` you shouldn't need to pass it using the with statement as it is available already as is.

I will comment back on this when a patch is done. :+1:

**Comment by lstables** [comment]
Awesome, thanks for the quick response and I'll look forward to the patch release ;)

**Comment by ReeceM** [comment]
@lstables please run a `composer update` to get the mocker class to update to [v1.1.1](https://github.com/ReeceM/mocker/releases/tag/v1.1.1).

**Comment by Qoraiche** [comment]
Thanks for the quick fix @ReeceM

**Comment by lstables** [comment]
Awesome thanks @ReeceM and @Qoraiche for this awesome package and fixes. All working just fine now.
