### ISSUE TITLE
Views and custom data

### ISSUE THREAD

**Issue by dily86** [Qoraiche/laravel-mail-editor#5]
Thank you for this excellent package.  I installed it in a project using laravel 5.7 however when I do php artisan vendor:publish I don't have the views.  But I absolutely need to customize them.  Another problem is that the variables do not appear when I edit the template of an email.
Thank you in advance for your help.

**Comment by Qoraiche** [comment]
Hi @dily86,

Just to let you know that `vendor:publish` will just publish the public application assets (js, css, etc..) and the configuration file, the email templates will not be published because you can edit them directly through the application (editor). can you please share your mailable class?

**Comment by dily86** [comment]
Hi,
This is my mailable class:
`<?php

namespace App\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;
use Illuminate\Contracts\Queue\ShouldQueue;

class Test extends Mailable
{
    use Queueable, SerializesModels;

    publi $username = 'Anne';

    /**
     * Create a new message instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Build the message.
     *
     * @return $this
     */
    public function build()
    {
        return $this->markdown('maileclipse::templates.myTemplate');
    }
}
`

**Comment by Qoraiche** [comment]
Currently, the editor preview will output a simple variable as follows: `{{ varname }}`, in your case: `{{ username }}`. in case you are using Models, the package will look for the equivalent factory in the mailable constructor and check if the dependency is an eloquent model.

**Comment by Qoraiche** [comment]
@dily86 if you still have more questions, you can simply reopen this issue.

Thank you!

**Comment by salhdev** [comment]
> Hi @dily86,
> 
> you have to know that `vendor:publish` will just publish the application public assets - which you will not need - and the configuration file, the email templates are not going to be published because you can edit them directly through the application (editor). also, can you please share your mailable class?

Hi, I think there should be a vendor:publish to copy all view into the resources/views/vendor/maileclipse in order to allow for customisation or just mention it in the Readme!
I have copied it manually and all my changes take immediate effect.

**Comment by Qoraiche** [comment]
@dily86 i don't understand, can you explain more?

**Comment by salhdev** [comment]
Hi @Qoraiche and @dily86 

All you need to do is replace the following line in the serviceprovider boot method : 
`        $this->loadViewsFrom(__DIR__.'/../resources/views', 'maileclipse'); `
by
```
	$viewPath = __DIR__.'/../resources/views';
        $this->loadViewsFrom($viewPath, 'maileclipse');
        $this->publishes([
          $viewsPath => base_path('resources/views/vendor/maileclipse'),
        ], 'views');
``` 
And then when you do a : 
`php artisan vendor:publish --provider="qoraiche\mailEclipse\mailEclipseServiceProvider" --tag=views`

It will copy the views in the resources/views/vendor/maileclipse directory where you can edit them and the package will use those instead of the original ones.

@dily86 you can also just do it manually and copy the files from the vendor/qoraiche/laravel-mail-editor/resources/views to resources/views/vendor/maileclipse.
You don't have to copy them all, just select the ones you want to change.

I hope this helps !

**Comment by Qoraiche** [comment]
@salhdev Please pull request this changes and i will review it

Thanks,
