### ISSUE TITLE
Exception: Function ReflectionType::__toString() is deprecated

### ISSUE THREAD

**Issue by 4n70w4** [Qoraiche/laravel-mail-editor#82]
![image](https://user-images.githubusercontent.com/38257723/77555397-40544300-6ec8-11ea-8e0c-c2a7c09778a1.png)
![image](https://user-images.githubusercontent.com/38257723/77555456-4d713200-6ec8-11ea-94c7-25e77f4ac235.png)

**Comment by Qoraiche** [comment]
Hey @4n70w4. sorry for the late reply, could you please tell which laravel version you're using?

**Comment by ncatanchin** [comment]
Hi @Qoraiche - I'm seeing this same issue on latest Laravel 6.18.13 - but for me it has been present since I installed the package about 4 weeks ago - Laravel 6.18.6

**Comment by ReeceM** [comment]
Hi @ncatanchin and @Qoraiche,

It appears that it is a function that I added a while back to split some functionality and has to do with finding the types when there was an issue with the types, added in PR #53

If it is alright, I can have a look at resolving this next week on Monday or so?

**Comment by Qoraiche** [comment]
thanks @ReeceM

**Comment by ReeceM** [comment]
For knowing what the problem, it is a deprecation that came in since php version 7.1 as the `__toString` method was removed from the `ReflectionType` class.

It was replaced with an undocumented method called [getName()](https://www.php.net/manual/en/class.reflectiontype.php#124658), but only in version >=7.1.

Due to the fact that this method doesn't exist in version before 7.1 it throughs a similar error for getName being undefined. For that reason I will make it backwards compatible so that versions of laravel 5.x and up will work still.
