### ISSUE TITLE
Mailables Generate in the default folder even though mailables_dir is set

### ISSUE THREAD

**Issue by UdyW** [Qoraiche/laravel-mail-editor#88]
In the config the the mailables_dir is set

` 'mailables_dir' => app_path('Mail/CustomTemplates')`

But when mailables are generated they would still be generated in the default Mail folder.

**Comment by Idimma** [comment]
This is due to the namespace App\Mail

**Comment by ReeceM** [comment]
For anyone who will work on this in the coming Hacktoberfest season. Please mark that you would like to work on this.

**Comment by ReeceM** [comment]
Also the `mailables_dir` config value seems to handle where the templates.json file is stored, it is never referenced in the actual function in creating a new mailable, although it is used when deleting the mailable, so that is a plus as adding it to the create function would not break that part.

If you do use the naming from the mailables_dir, you will actually get the entire real path of the app, it will then create a really weird namespace under the mail area. 

The change would probably be to make the config value reflect a namespace without the `app_path` call, and do that in the function calls when needing the actual path to the file.

Then use the config value as the namespace and also the file path to resolve when creating the mailables.
